version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: project24-app
        restart: unless-stopped
        ports:
            - "9000:9000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8
        container_name: project24-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rizal8
            MYSQL_DATABASE: pc24_project
            MYSQL_USER: rizal
            MYSQL_PASSWORD: rizal8
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: project24-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    dbdata:
