version: "3.8"

services:
  app-staging:
    image: rizshinoda/project24-laravel:staging
    container_name: app-staging
    restart: unless-stopped

    env_file:
      - .env.staging
    networks:
      - laravel
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rizal8
      MYSQL_DATABASE: pc24_project
      MYSQL_USER: rizal
      MYSQL_PASSWORD: rizal8
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx-staging:
    image: nginx:alpine
    container_name: nginx-staging
    ports:
      - "8100:80"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - app-staging
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
